In [ ]:
import pandas as pd

In [ ]:
# Load the dataset
df = pd.read_csv('/content/telecom_churn_data.csv')

# Display the first few rows to understand the structure
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

In [ ]:
df.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [ ]:
# Get descriptive statistics
print(df.describe(include='all'))

        customerID gender  SeniorCitizen Partner Dependents       tenure  \
count         7043   7043    7043.000000    7043       7043  7043.000000
unique        7043      2            NaN       2          2          NaN
top     7590-VHVEG   Male            NaN      No         No          NaN
freq             1   3555            NaN    3641       4933          NaN
mean           NaN    NaN       0.162147     NaN        NaN    32.371149
std            NaN    NaN       0.368612     NaN        NaN    24.559481
min            NaN    NaN       0.000000     NaN        NaN     0.000000
25%            NaN    NaN       0.000000     NaN        NaN     9.000000
50%            NaN    NaN       0.000000     NaN        NaN    29.000000
75%            NaN    NaN       0.000000     NaN        NaN    55.000000
max            NaN    NaN       1.000000     NaN        NaN    72.000000

       PhoneService MultipleLines InternetService OnlineSecurity  ...  \
count          7043          7043            7043           7043  ...
unique            2             3               3              3  ...
top             Yes            No     Fiber optic             No  ...
freq           6361          3390            3096           3498  ...
mean            NaN           NaN             NaN            NaN  ...
std             NaN           NaN             NaN            NaN  ...
min             NaN           NaN             NaN            NaN  ...
25%             NaN           NaN             NaN            NaN  ...
50%             NaN           NaN             NaN            NaN  ...
75%             NaN           NaN             NaN            NaN  ...
max             NaN           NaN             NaN            NaN  ...

       DeviceProtection TechSupport StreamingTV StreamingMovies  \
count              7043        7043        7043            7043
unique                3           3           3               3
top                  No          No          No              No
freq               3095        3473        2810            2785
mean                NaN         NaN         NaN             NaN
std                 NaN         NaN         NaN             NaN
min                 NaN         NaN         NaN             NaN
25%                 NaN         NaN         NaN             NaN
50%                 NaN         NaN         NaN             NaN
75%                 NaN         NaN         NaN             NaN
max                 NaN         NaN         NaN             NaN

              Contract PaperlessBilling     PaymentMethod MonthlyCharges  \
count             7043             7043              7043    7043.000000
unique               3                2                 4            NaN
top     Month-to-month              Yes  Electronic check            NaN
freq              3875             4171              2365            NaN
mean               NaN              NaN               NaN      64.761692
std                NaN              NaN               NaN      30.090047
min                NaN              NaN               NaN      18.250000
25%                NaN              NaN               NaN      35.500000
50%                NaN              NaN               NaN      70.350000
75%                NaN              NaN               NaN      89.850000
max                NaN              NaN               NaN     118.750000

        TotalCharges Churn
count           7043  7043
unique          6531     2
top                     No
freq              11  5174
mean             NaN   NaN
std              NaN   NaN
min              NaN   NaN
25%              NaN   NaN
50%              NaN   NaN
75%              NaN   NaN
max              NaN   NaN

[11 rows x 21 columns]

In [ ]:
# Convert 'TotalCharges' to numeric, forcing errors to NaN
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')

# Check for NaNs in 'TotalCharges'
print(df['TotalCharges'].isnull().sum())

# You can drop rows with NaN in 'TotalCharges' if necessary
df.dropna(subset=['TotalCharges'], inplace=True)

11

In [ ]:
# Check unique values in 'gender'
print("Unique values in 'gender':", df['gender'].unique())

# Check other categorical variables similarly
print("Unique values in 'Partner':", df['Partner'].unique())
print("Unique values in 'Dependents':", df['Dependents'].unique())
# Add more checks for other categorical variables as needed

Unique values in 'gender': ['Female' 'Male']
Unique values in 'Partner': ['Yes' 'No']
Unique values in 'Dependents': ['No' 'Yes']

In [ ]:
# Clean the 'gender' column (ensure it's consistent)
df['gender'] = df['gender'].astype(str).str.strip().str.lower()

# Map values
gender_mapping = {'male': 0, 'female': 1}
df['gender'] = df['gender'].map(gender_mapping)

# Check for NaNs after mapping
print("Number of NaN values in 'gender' after encoding:", df['gender'].isnull().sum())

Number of NaN values in 'gender' after encoding: 0

In [ ]:
# One-hot encode selected categorical variables
categorical_columns = ['Partner', 'Dependents', 'PhoneService', 'MultipleLines',
                       'InternetService', 'OnlineSecurity', 'OnlineBackup',
                       'DeviceProtection', 'TechSupport', 'StreamingTV',
                       'StreamingMovies', 'Contract', 'PaperlessBilling',
                       'PaymentMethod']

# Apply one-hot encoding
df = pd.get_dummies(df, columns=categorical_columns, drop_first=True)

# Check the DataFrame after encoding
print(df.head())

   customerID  gender  SeniorCitizen  tenure  MonthlyCharges  TotalCharges  \
0  7590-VHVEG       1              0       1           29.85         29.85
1  5575-GNVDE       0              0      34           56.95       1889.50
2  3668-QPYBK       0              0       2           53.85        108.15
3  7795-CFOCW       0              0      45           42.30       1840.75
4  9237-HQITU       1              0       2           70.70        151.65

  Churn  Partner_Yes  Dependents_Yes  PhoneService_Yes  ...  \
0    No         True           False             False  ...
1    No        False           False              True  ...
2   Yes        False           False              True  ...
3    No        False           False             False  ...
4   Yes        False           False              True  ...

   StreamingTV_No internet service  StreamingTV_Yes  \
0                            False            False
1                            False            False
2                            False            False
3                            False            False
4                            False            False

   StreamingMovies_No internet service  StreamingMovies_Yes  \
0                                False                False
1                                False                False
2                                False                False
3                                False                False
4                                False                False

   Contract_One year  Contract_Two year  PaperlessBilling_Yes  \
0              False              False                  True
1               True              False                 False
2              False              False                  True
3               True              False                 False
4              False              False                  True

   PaymentMethod_Credit card (automatic)  PaymentMethod_Electronic check  \
0                                  False                            True
1                                  False                           False
2                                  False                           False
3                                  False                           False
4                                  False                            True

   PaymentMethod_Mailed check
0                       False
1                        True
2                        True
3                       False
4                       False

[5 rows x 32 columns]

In [ ]:
# Map values for 'Churn'
churn_mapping = {'No': 0, 'Yes': 1}
df['Churn'] = df['Churn'].map(churn_mapping)

# Check for NaNs after mapping
print("Number of NaN values in 'Churn' after encoding:", df['Churn'].isnull().sum())

Number of NaN values in 'Churn' after encoding: 0

In [ ]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
Index: 7032 entries, 0 to 7042
Data columns (total 32 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   customerID                             7032 non-null   object
 1   gender                                 7032 non-null   int64
 2   SeniorCitizen                          7032 non-null   int64
 3   tenure                                 7032 non-null   int64
 4   MonthlyCharges                         7032 non-null   float64
 5   TotalCharges                           7032 non-null   float64
 6   Churn                                  7032 non-null   int64
 7   Partner_Yes                            7032 non-null   bool
 8   Dependents_Yes                         7032 non-null   bool
 9   PhoneService_Yes                       7032 non-null   bool
 10  MultipleLines_No phone service         7032 non-null   bool
 11  MultipleLines_Yes                      7032 non-null   bool
 12  InternetService_Fiber optic            7032 non-null   bool
 13  InternetService_No                     7032 non-null   bool
 14  OnlineSecurity_No internet service     7032 non-null   bool
 15  OnlineSecurity_Yes                     7032 non-null   bool
 16  OnlineBackup_No internet service       7032 non-null   bool
 17  OnlineBackup_Yes                       7032 non-null   bool
 18  DeviceProtection_No internet service   7032 non-null   bool
 19  DeviceProtection_Yes                   7032 non-null   bool
 20  TechSupport_No internet service        7032 non-null   bool
 21  TechSupport_Yes                        7032 non-null   bool
 22  StreamingTV_No internet service        7032 non-null   bool
 23  StreamingTV_Yes                        7032 non-null   bool
 24  StreamingMovies_No internet service    7032 non-null   bool
 25  StreamingMovies_Yes                    7032 non-null   bool
 26  Contract_One year                      7032 non-null   bool
 27  Contract_Two year                      7032 non-null   bool
 28  PaperlessBilling_Yes                   7032 non-null   bool
 29  PaymentMethod_Credit card (automatic)  7032 non-null   bool
 30  PaymentMethod_Electronic check         7032 non-null   bool
 31  PaymentMethod_Mailed check             7032 non-null   bool
dtypes: bool(25), float64(2), int64(4), object(1)
memory usage: 611.2+ KB
None

In [ ]:
df.head()

,customerID,gender,SeniorCitizen,tenure,MonthlyCharges,TotalCharges,Churn,Partner_Yes,Dependents_Yes,PhoneService_Yes,...,StreamingTV_No internet service,StreamingTV_Yes,StreamingMovies_No internet service,StreamingMovies_Yes,Contract_One year,Contract_Two year,PaperlessBilling_Yes,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,7590-VHVEG,1,0,1,29.85,29.85,0,True,False,False,...,False,False,False,False,False,False,True,False,True,False
1,5575-GNVDE,0,0,34,56.95,1889.50,0,False,False,True,...,False,False,False,False,True,False,False,False,False,True
2,3668-QPYBK,0,0,2,53.85,108.15,1,False,False,True,...,False,False,False,False,False,False,True,False,False,True
3,7795-CFOCW,0,0,45,42.30,1840.75,0,False,False,False,...,False,False,False,False,True,False,False,False,False,False
4,9237-HQITU,1,0,2,70.70,151.65,1,False,False,True,...,False,False,False,False,False,False,True,False,True,False

In [ ]:
# Save in the current directory
df.to_csv('processed_telco_customer_churn.csv', index=False)

In [ ]:
import os
print(os.getcwd())  # This will show the current directory path

/content

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7032 entries, 0 to 7042
Data columns (total 32 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   customerID                             7032 non-null   object
 1   gender                                 7032 non-null   int64
 2   SeniorCitizen                          7032 non-null   int64
 3   tenure                                 7032 non-null   int64
 4   MonthlyCharges                         7032 non-null   float64
 5   TotalCharges                           7032 non-null   float64
 6   Churn                                  7032 non-null   int64
 7   Partner_Yes                            7032 non-null   bool
 8   Dependents_Yes                         7032 non-null   bool
 9   PhoneService_Yes                       7032 non-null   bool
 10  MultipleLines_No phone service         7032 non-null   bool
 11  MultipleLines_Yes                      7032 non-null   bool
 12  InternetService_Fiber optic            7032 non-null   bool
 13  InternetService_No                     7032 non-null   bool
 14  OnlineSecurity_No internet service     7032 non-null   bool
 15  OnlineSecurity_Yes                     7032 non-null   bool
 16  OnlineBackup_No internet service       7032 non-null   bool
 17  OnlineBackup_Yes                       7032 non-null   bool
 18  DeviceProtection_No internet service   7032 non-null   bool
 19  DeviceProtection_Yes                   7032 non-null   bool
 20  TechSupport_No internet service        7032 non-null   bool
 21  TechSupport_Yes                        7032 non-null   bool
 22  StreamingTV_No internet service        7032 non-null   bool
 23  StreamingTV_Yes                        7032 non-null   bool
 24  StreamingMovies_No internet service    7032 non-null   bool
 25  StreamingMovies_Yes                    7032 non-null   bool
 26  Contract_One year                      7032 non-null   bool
 27  Contract_Two year                      7032 non-null   bool
 28  PaperlessBilling_Yes                   7032 non-null   bool
 29  PaymentMethod_Credit card (automatic)  7032 non-null   bool
 30  PaymentMethod_Electronic check         7032 non-null   bool
 31  PaymentMethod_Mailed check             7032 non-null   bool
dtypes: bool(25), float64(2), int64(4), object(1)
memory usage: 611.2+ KB

In [ ]:
# Convert all boolean columns to integer type (0 and 1)
df = df.astype({col: 'int' for col in df.select_dtypes(include=['bool']).columns})

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7032 entries, 0 to 7042
Data columns (total 32 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   customerID                             7032 non-null   object
 1   gender                                 7032 non-null   int64
 2   SeniorCitizen                          7032 non-null   int64
 3   tenure                                 7032 non-null   int64
 4   MonthlyCharges                         7032 non-null   float64
 5   TotalCharges                           7032 non-null   float64
 6   Churn                                  7032 non-null   int64
 7   Partner_Yes                            7032 non-null   int64
 8   Dependents_Yes                         7032 non-null   int64
 9   PhoneService_Yes                       7032 non-null   int64
 10  MultipleLines_No phone service         7032 non-null   int64
 11  MultipleLines_Yes                      7032 non-null   int64
 12  InternetService_Fiber optic            7032 non-null   int64
 13  InternetService_No                     7032 non-null   int64
 14  OnlineSecurity_No internet service     7032 non-null   int64
 15  OnlineSecurity_Yes                     7032 non-null   int64
 16  OnlineBackup_No internet service       7032 non-null   int64
 17  OnlineBackup_Yes                       7032 non-null   int64
 18  DeviceProtection_No internet service   7032 non-null   int64
 19  DeviceProtection_Yes                   7032 non-null   int64
 20  TechSupport_No internet service        7032 non-null   int64
 21  TechSupport_Yes                        7032 non-null   int64
 22  StreamingTV_No internet service        7032 non-null   int64
 23  StreamingTV_Yes                        7032 non-null   int64
 24  StreamingMovies_No internet service    7032 non-null   int64
 25  StreamingMovies_Yes                    7032 non-null   int64
 26  Contract_One year                      7032 non-null   int64
 27  Contract_Two year                      7032 non-null   int64
 28  PaperlessBilling_Yes                   7032 non-null   int64
 29  PaymentMethod_Credit card (automatic)  7032 non-null   int64
 30  PaymentMethod_Electronic check         7032 non-null   int64
 31  PaymentMethod_Mailed check             7032 non-null   int64
dtypes: float64(2), int64(29), object(1)
memory usage: 1.8+ MB

In [ ]:
# Save in the current directory
df.to_csv('processed_telco_customer_churn.csv', index=False)

In [ ]:
import os
print(os.getcwd())

/content